src/report_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sales.urls', namespace='sales')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/reports/urls.py
from django.urls import path
from .views import (
    create_report_view,
    ReportListView,
    ReportDetailView,
    render_pdf_view,
)

app_name = 'reports'

urlpatterns = [
    path('save/', create_report_view, name='save-report'),
    path('<pk>/', ReportDetailView.as_view(), name='report'),
    path('', ReportListView.as_view(), name = 'reports'),
    path('<pk>/pdf/', render_pdf_view, name = 'pdf'),
]

src/sales/urls.py
from django.urls import path
from .views import (
    home_view,
    SalesView,
    SalesDetailView,
    UploadTemplateView,
    csv_upload_view,
)

app_name = 'sales'

urlpatterns = [
    path('', home_view, name='home'),
    path('sales/', SalesView.as_view(), name='list'),
    path('detail/<pk>/', SalesDetailView.as_view(), name='detail'),
    path('from-file/', UploadTemplateView.as_view(), name='from-file'),
    path('upload/', csv_upload_view, name='upload'),

]

src/reports/models.py
from django.db import models
from profiles.models import Profile
from django.urls import reverse
# Create your models here.


class Report(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='reports', blank=True)
    remarks = models.TextField()
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('reports:report', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ('-created',)

src/reports/forms.py
from django import forms
from .models import Report


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = [
            'name',
            'remarks'
            ]

src/reports/views.py
from django.shortcuts import render, get_object_or_404
from django.template.loader import get_template
from profiles.models import Profile
from django.http import JsonResponse, HttpResponse
from xhtml2pdf import pisa

from .utils import get_report_image
from .models import Report
from django.views.generic import ListView, DetailView

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ReportForm
# Create your views here.

class ReportListView(LoginRequiredMixin, ListView):
    model = Report
    template_name = 'reports/main.html'

class ReportDetailView(LoginRequiredMixin, DetailView):
    model = Report
    template_name = 'reports/detail.html'

@login_required
def create_report_view(request):
    if request.is_ajax():
        name = request.POST.get('name')
        remarks = request.POST.get('remarks')
        image = request.POST.get('image')
        img = get_report_image(image)
        author = Profile.objects.get(user=request.user)
        Report.objects.create(name=name, remarks=remarks, image=img, author=author)
    return JsonResponse({})

# def create_report_view(request):
#     form = ReportForm(request.POST or None)
#     if request.is_ajax():
#         image = request.POST.get('image')
#         img = get_report_image(image)
#         author = Profile.objects.get(user=request.user)
#
#         if form.is_valid():
#             instance = form.save(commit=False)
#             instance.image = img
#             instance.author = author
#             instance.save()
#
#     return JsonResponse({})

@login_required
def render_pdf_view(request, pk):
    template_path = 'reports/pdf.html'
    #obj = Report.objects.get(id=pk)
    obj = get_object_or_404(Report, id=pk)
    context = {'obj': obj}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    # if dowlnoad:
    #response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    #if display:
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

src/reports/templates/reports/detail.html
{% extends 'base.html' %}
{% block title %}
{{ object.name }}
{% endblock title %}

{% block content %}
    {% if object.image %}
    <img src="{{ object.image.url }}" class="img-fuid" alt="{{ object.name }}">
    {% endif %}
    <br />
    <h3>Remarks</h3>
    <p>{{ object.remarks }}</p>
    <hr>
    <p>author <b> {{ object.author.user.username }} </b></p>
    <p>created <b> {{ object.created }} </b></p>
{% endblock content %}

src/reports/templates/reports/main.html
{% extends 'base.html' %}
{% block title %}
reports
{% endblock title %}

{% block content %}
reports
<hr>

{% for obj in object_list %}
    <div class="card mb-3" style="width: 18rem;">
        {% if obj.image %}
            <img src="{{ obj.image.url }}" class="card-img-top" alt="{{ obj.name }}">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ obj.name }}</h5>
             <p class="card-text">{{ obj.remarks|truncatewords:2 }}</p>
             <a href="{{ obj.get_absolute_url }}" class="btn btn-primary">Detail View: {{ obj.name }} </a>
            <br />
            <a href="{% url 'reports:pdf' obj.pk %}" class="btn btn-danger mt-2"> PDF </a>
         </div>
    </div>

<br />
{% endfor %}
{% endblock content %}

src/reports/templates/reports/pdf.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>PDF {{ obj.name }}</title>
  <style>
    .image {
      width: 100%;
      height: auto;
      }

  </style>
</head>
<body>
  <h1>{{ obj.name }}</h1>
  <hr>
  <img src="{{ obj.image.path }}" class="image">
   <br />
    <h3>Remarks</h3>
    <p>{{ obj.remarks }}</p>
    <hr>
    <p>author <b> {{ obj.author.user.username }} </b></p>
    <p>created <b> {{ obj.created }} </b></p>
</body>
</html>